"""update celery_task_executions table indexes

Revision ID: 243ca8b683b0
Revises: b9f9e870b09b
Create Date: 2025-08-03 23:15:43.860171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '243ca8b683b0'
down_revision: Union[str, None] = 'b9f9e870b09b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ixz_task_name_args_celery_hash', 'celery_task_executions', ['task_name', 'task_args_hash', 'celery_task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixz_task_name_args_celery_hash', table_name='celery_task_executions')
    # ### end Alembic commands ###
